### ISSUE TITLE
Class Data is failing when one of the input list is empty

### ISSUE THREAD

**Issue by eduardcd** [eduardcd/AST-Assignments#3]
The class Data is failing the method compute when one of the input list is empty.

The result should be 
[('knife',1, .99), ('scissor', 2, .65), ('spoon', 3, .33)]

eduardo@eduardo-AERO-15XV8:~/Documents/AST/Project/project$ PYTHONPATH=. py.test -v
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/eduardo/Documents/AST/Project/project, inifile: 
collected 8 items 

test_Data.py::test_calculate PASSED
test_Data.py::test_calculate2 PASSED
test_Data_update_1.py::test_calculate1 FAILED
test_Data_update_1.py::test_calculate2 PASSED
test_Data_update_1.py::test_calculate3 FAILED
test_Data_update_1.py::test_calculate4 PASSED
test_Data_update_1.py::test_calculate5 FAILED
test_Data_update_1.py::test_calculate6 FAILED

=================================== FAILURES ===================================
_______________________________ test_calculate3 ________________________________

    def test_calculate3():
        rgbd = [('knife',1, .99), ('scissor', 2, .65), ('spoon', 3, .33)]
        rgb =  []
>       data3 = Data(rgbd, rgb)

test_Data_update_1.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <code_1.Data instance at 0x7f41db8a2830>
rgbd = [('knife', 1, 0.99), ('scissor', 2, 0.65), ('spoon', 3, 0.33)], rgb = []

    def __init__(self, rgbd, rgb):
        if len(rgbd) != len(rgb):
>           raise ValueError('Invalid Data')
E           ValueError: Invalid Data

code_1.py:7: ValueError

**Comment by vahmohh** [comment]
It should be fixed now.
